name: Deploy to Dreamhost

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: prod  # Use the prod environment to access secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, openssl, zip, unzip
        coverage: none
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install PHP dependencies
      run: composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist
      
    - name: Install Node dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Create deployment archive
      run: |
        # Create staging directory for deployment
        mkdir -p deploy-staging
        
        # Copy files to staging, excluding development files
        rsync -av --progress . deploy-staging/ \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='.env' \
          --exclude='.env.production' \
          --exclude='.env.example' \
          --exclude='.env.local' \
          --exclude='.env.*.local' \
          --exclude='tests' \
          --exclude='storage/logs/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          --exclude='storage/app/public/*' \
          --exclude='README.md' \
          --exclude='CHANGELOG.md' \
          --exclude='TODO.md' \
          --exclude='phpunit.xml' \
          --exclude='.phpunit.cache' \
          --exclude='*.log' \
          --exclude='*.tmp' \
          --exclude='.DS_Store' \
          --exclude='Thumbs.db' \
          --exclude='deploy-staging'
        
        # Create tar archive from staging directory
        tar -czf deploy.tar.gz -C deploy-staging .
          
    - name: Deploy to Dreamhost via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        script: |
          # Navigate to your domain directory
          cd ${{ secrets.DREAMHOST_PATH }}
          
          # Backup environment files before deployment
          if [ -f "ealifecycle/.env.production" ]; then
            echo "Backing up .env.production"
            cp ealifecycle/.env.production /tmp/env-production-backup
          fi
          
          if [ -f "ealifecycle/.env" ]; then
            echo "Backing up .env"
            cp ealifecycle/.env /tmp/env-backup
          fi
          
          # Create backup of current deployment
          if [ -d "ealifecycle" ]; then
            rm -rf ealifecycle-backup
            mv ealifecycle ealifecycle-backup
          fi
          
          # Create new deployment directory
          mkdir -p ealifecycle
          
    - name: Upload deployment package
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        source: "deploy.tar.gz"
        target: "${{ secrets.DREAMHOST_PATH }}/ealifecycle/"
        
    - name: Extract and configure application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.DREAMHOST_PATH }}/ealifecycle
          
          # Check and use PHP 8.4 if available on Dreamhost
          if command -v php8.4 &> /dev/null; then
            export PHP_BINARY=php8.4
            echo "Using PHP 8.4"
          elif command -v php8.3 &> /dev/null; then
            export PHP_BINARY=php8.3
            echo "Using PHP 8.3"
          elif command -v php8.2 &> /dev/null; then
            export PHP_BINARY=php8.2
            echo "Using PHP 8.2"
          else
            export PHP_BINARY=php
            echo "Using default PHP version"
          fi
          
          # Check PHP version meets requirements
          $PHP_BINARY -v
          
          # Extract deployment package
          tar -xzf deploy.tar.gz
          rm deploy.tar.gz
          
          # Restore environment files from backup
          if [ -f "/tmp/env-production-backup" ]; then
            echo "Restoring .env.production from backup"
            cp /tmp/env-production-backup .env.production
            rm /tmp/env-production-backup
          fi
          
          if [ -f "/tmp/env-backup" ]; then
            echo "Restoring .env from backup"
            cp /tmp/env-backup .env
            rm /tmp/env-backup
          else
            # Only create .env from .env.production if no existing .env was backed up
            if [ -f ".env.production" ]; then
              echo "Creating .env from .env.production"
              cp .env.production .env
            else
              echo "WARNING: No .env.production file found for environment setup"
            fi
          fi
          
          # Ensure .htaccess file exists in public directory for Laravel routing
          if [ ! -f "public/.htaccess" ]; then
            echo "Creating .htaccess file for Laravel routing"
            echo "<IfModule mod_rewrite.c>" > public/.htaccess
            echo "    <IfModule mod_negotiation.c>" >> public/.htaccess
            echo "        Options -MultiViews -Indexes" >> public/.htaccess
            echo "    </IfModule>" >> public/.htaccess
            echo "" >> public/.htaccess
            echo "    RewriteEngine On" >> public/.htaccess
            echo "" >> public/.htaccess
            echo "    # Handle Authorization Header" >> public/.htaccess
            echo "    RewriteCond %{HTTP:Authorization} ." >> public/.htaccess
            echo "    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]" >> public/.htaccess
            echo "" >> public/.htaccess
            echo "    # Redirect Trailing Slashes If Not A Folder..." >> public/.htaccess
            echo "    RewriteCond %{REQUEST_FILENAME} !-d" >> public/.htaccess
            echo "    RewriteCond %{REQUEST_URI} (.+)/$" >> public/.htaccess
            echo "    RewriteRule ^ %1 [L,R=301]" >> public/.htaccess
            echo "" >> public/.htaccess
            echo "    # Send Requests To Front Controller..." >> public/.htaccess
            echo "    RewriteCond %{REQUEST_FILENAME} !-d" >> public/.htaccess
            echo "    RewriteCond %{REQUEST_FILENAME} !-f" >> public/.htaccess
            echo "    RewriteRule ^ index.php [L]" >> public/.htaccess
            echo "</IfModule>" >> public/.htaccess
          fi
          
          # Set proper permissions
          chmod -R 755 storage bootstrap/cache
          chmod -R 777 storage/logs storage/framework/cache storage/framework/sessions storage/framework/views
          
          # Install/update Composer dependencies with specific PHP version
          $PHP_BINARY $(which composer) install --optimize-autoloader --no-dev --no-interaction --ignore-platform-req=php
          
          # Laravel deployment commands with specific PHP version
          echo "Clearing all Laravel caches before deployment..."
          $PHP_BINARY artisan optimize:clear || true
          
          echo "Running database migrations..."
          $PHP_BINARY artisan migrate --force
          
          echo "Optimizing Laravel for production..."
          $PHP_BINARY artisan config:cache
          $PHP_BINARY artisan route:cache
          $PHP_BINARY artisan view:cache
          
          echo "Final cache optimization and cleanup..."
          # Clear any problematic caches that might cause 405 errors
          $PHP_BINARY artisan config:clear
          $PHP_BINARY artisan route:clear
          # Keep view and config caches cleared to prevent 405 issues
          
          echo "Setting final permissions..."
          chmod -R 755 public/
          chmod 644 public/index.php
          
          # Create symlink to web directory if it doesn't exist
          if [ ! -L "${{ secrets.DREAMHOST_PATH }}/4xhacker.com/ealifecycle" ]; then
            ln -s ${{ secrets.DREAMHOST_PATH }}/ealifecycle/public ${{ secrets.DREAMHOST_PATH }}/4xhacker.com/ealifecycle
          fi
          
          echo "Deployment completed successfully!"
          
    - name: Rollback on failure
      if: failure()
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.DREAMHOST_PATH }}
          
          # Restore environment files from backup if they exist
          if [ -f "/tmp/env-production-backup" ]; then
            echo "Restoring .env.production from backup during rollback"
            cp /tmp/env-production-backup ealifecycle/.env.production 2>/dev/null || true
            rm /tmp/env-production-backup
          fi
          
          if [ -f "/tmp/env-backup" ]; then
            echo "Restoring .env from backup during rollback"
            cp /tmp/env-backup ealifecycle/.env 2>/dev/null || true
            rm /tmp/env-backup
          fi
          
          # Perform rollback to previous version
          if [ -d "ealifecycle-backup" ]; then
            rm -rf ealifecycle
            mv ealifecycle-backup ealifecycle
            echo "Rollback completed - restored previous version"
          fi
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment to Dreamhost completed successfully!"
        else
          echo "❌ Deployment failed - check logs and rollback if necessary"
        fi 