name: Deploy to Dreamhost

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: # Allow manual deployment

jobs:
  run-tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Setup test database
      run: |
        touch database/database.sqlite
        cp .env.example .env
        php artisan key:generate
        php artisan migrate --force

    - name: Run tests
      run: vendor/bin/phpunit

  validate-composer:
    name: Validate composer.lock
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none
        
    - name: Get Composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Validate composer.lock is up-to-date
      run: |
        composer validate --no-check-all --strict
        git diff --exit-code -- composer.lock

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    environment: prod  # Use the prod environment to access secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, openssl, zip, unzip
        coverage: none
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install PHP dependencies
      run: composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist
      
    - name: Install Node dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Prepare deployment package
      run: |
        # Create staging directory for deployment
        mkdir -p deploy-staging
        
        # Copy files to staging, excluding development files
        rsync -av --progress . deploy-staging/ \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='.env' \
          --exclude='.env.production' \
          --exclude='.env.example' \
          --exclude='.env.local' \
          --exclude='.env.*.local' \
          --exclude='tests' \
          --exclude='storage/logs/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          --exclude='storage/app/public/*' \
          --exclude='README.md' \
          --exclude='CHANGELOG.md' \
          --exclude='TODO.md' \
          --exclude='phpunit.xml' \
          --exclude='.phpunit.cache' \
          --exclude='*.log' \
          --exclude='*.tmp' \
          --exclude='.DS_Store' \
          --exclude='Thumbs.db' \
          --exclude='deploy-staging'
          # DO NOT exclude public/build so Vite manifest is deployed
        
        # List contents to verify everything is there
        echo "=== Contents of deploy-staging ==="
        ls -la deploy-staging/
        
        # Create tar archive from staging directory  
        tar -czf deploy.tar.gz -C deploy-staging .
        
        # Verify tar contents
        echo "=== Contents of deploy.tar.gz ==="
        tar -tzf deploy.tar.gz | head -20
          
    - name: Upload deployment package
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        source: "deploy.tar.gz"
        target: "${{ secrets.DREAMHOST_PATH }}"
        strip_components: 0

    - name: Deploy to Dreamhost via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        script: |
          # Navigate to your domain directory
          cd ${{ secrets.DREAMHOST_PATH }}
          
          # Verify deployment package exists
          if [ ! -f "deploy.tar.gz" ]; then
            echo "Error: deploy.tar.gz not found!"
            exit 1
          fi
          
          # Backup environment files before deployment
          if [ -f "ealifecycle/.env.production" ]; then
            echo "Backing up .env.production"
            cp ealifecycle/.env.production /tmp/env-production-backup
          fi
          
          if [ -f "ealifecycle/.env" ]; then
            echo "Backing up .env"
            cp ealifecycle/.env /tmp/env-backup
          fi
          
          # Create backup of current deployment
          if [ -d "ealifecycle" ]; then
            rm -rf ealifecycle-backup
            mv ealifecycle ealifecycle-backup
          fi
          
          # Create new deployment directory
          mkdir -p ealifecycle
          
          # Extract new deployment
          echo "Extracting deployment package..."
          tar -xzf deploy.tar.gz -C ealifecycle
          
          # Verify extraction
          if [ ! -d "ealifecycle/storage" ]; then
            echo "Error: Extraction failed - storage directory not found!"
            exit 1
          fi
          
          # Restore environment files
          if [ -f "/tmp/env-production-backup" ]; then
            cp /tmp/env-production-backup ealifecycle/.env.production
          fi
          
          if [ -f "/tmp/env-backup" ]; then
            cp /tmp/env-backup ealifecycle/.env
          fi
          
          # Install dependencies and build assets
          cd ealifecycle
          echo "Installing dependencies..."
          which composer || echo "Composer not found in PATH"
          which npm || echo "NPM not found in PATH"
          
          # Use full paths for commands
          /usr/local/bin/composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist
          /usr/local/bin/npm ci
          /usr/local/bin/npm run build
          
          # Clear all caches
          echo "Clearing caches..."
          php artisan optimize:clear
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          
          # Optimize for production
          echo "Optimizing for production..."
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          # Cleanup
          echo "Cleaning up..."
          rm -f deploy.tar.gz
          
          echo "Deployment completed successfully!"
          
    - name: Rollback on failure
      if: failure()
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DREAMHOST_HOST }}
        username: ${{ secrets.DREAMHOST_USERNAME }}
        key: ${{ secrets.DREAMHOST_SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.DREAMHOST_PATH }}
          
          # Restore environment files from backup if they exist
          if [ -f "/tmp/env-production-backup" ]; then
            echo "Restoring .env.production from backup during rollback"
            cp /tmp/env-production-backup ealifecycle/.env.production 2>/dev/null || true
            rm /tmp/env-production-backup
          fi
          
          if [ -f "/tmp/env-backup" ]; then
            echo "Restoring .env from backup during rollback"
            cp /tmp/env-backup ealifecycle/.env 2>/dev/null || true
            rm /tmp/env-backup
          fi
          
          # Perform rollback to previous version
          if [ -d "ealifecycle-backup" ]; then
            rm -rf ealifecycle
            mv ealifecycle-backup ealifecycle
            echo "Rollback completed - restored previous version"
          fi
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment to Dreamhost completed successfully!"
        else
          echo "❌ Deployment failed - check logs and rollback if necessary"
        fi 